version: '3'

services:
  betest:
    build: .
    image: image_augi_betest
    environment:
      - MONGO_URI=mongodb://mongo:27017/db_augi_betest
      - PORT=5000
      - BROKER=kafka:9092
      - USER_TOPIC=kafka_augi_betest
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    networks:
      - backend-network

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - backend-network

  # for debugging db
  mongo-express:
    image: mongo-express
    pull_policy: if_not_present
    environment:
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
    ports:
      - "3002:8081"
    networks:
      - backend-network
    depends_on:
      - mongo

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend-network

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - backend-network

volumes:
  dbdata:


networks:
  backend-network:
    driver: bridge
